site_name: Omar's Pentest Cheatsheets
site_description: 'Active Directory and Internal Pentest Cheatsheets'
site_url: https://00xmora.github.io

# repo_url: https://github.com/yourusername
# edit_uri: blob/main/docs/

theme:
  name: material
  custom_dir: overrides
  color_mode: auto
  user_color_mode_toggle: true
  icon:
    repo: fontawesome/brands/github
    logo: material/server-security
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple      
      accent: deep orange 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple      
      accent: deep orange 
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.tabs.link
    - content.tooltips
    - content.footnotes
    - content.social
    - navigation.footer
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tabs
    - search.share
    - search.suggest


extra_css:
  - custom.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - search
  - git-revision-date-localized


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OmarSamy7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/Omar-Samy7/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Omar_Samy7
    - icon: fontawesome/brands/medium
      link: https://medium.com/@OmarSamy7
      image: /assets/profile.png


nav:
  - Home: /
  - Writeups: writeups/
  - Research & things: research/
  - About: about/