site_name: Omar Samy | Cybersecurity Blog & things
site_description: Research, writeups, and practical notes on web security, pentesting, and more.
site_url: https://00xmora.github.io

repo_url: https://github.com/00xmora/00xmora.github.io

theme:
  name: material
  custom_dir: overrides
  color_mode: auto
  user_color_mode_toggle: true
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
    social:
      # GitHub
      - icon: fontawesome/brands/github
        link: https://github.com/00xmora
      # Twitter/X
      - icon: fontawesome/brands/x-twitter
        link: https://twitter.com/00xmora
      # LinkedIn
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/00xmora

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple      
      accent: deep orange 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple      
      accent: deep orange 
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.tooltips
    - content.footnotes
    - content.social
    - navigation.footer
    - navigation.expand
    - navigation.tracking
    - navigation.sections  # For collapsible sections
    - navigation.top
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.tabs
    - search.share
    - search.suggest


extra_css:
  - custom.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized
  - meta
  - sitemap:
      changefreq: daily
      priority: 0.5
  - seo

  - minify:
      minify_html: true

  - social:
      cards: true
      cards_layout_options:
        color: "#ffffff"
        font_family: Bebas Neue
        logo: assets/images/logo.png



nav:
  - Home: index.md
  - Writeups:
      - Overview: writeups/index.md
      - Android: 
          - hextree labs soliutions: writeups/android/hextree-labs-soliutions/index.md
  - Research: research/index.md
  - About: about.md




extra:
  favicon: assets/images/logo.png
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/00xmora
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/00xmora
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/00xmora
      name: LinkedIn
  robots: |
    User-agent: *
    Allow: /
    Sitemap: https://00xmora.github.io/sitemap.xml
