name: Deploy MkDocs

on:
  push:
    branches:
      - main  # أو اسم الفرع بتاعك

permissions:
  contents: write  # عشان يقدر يعمل push للـ gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-material[optional]
          pip install mkdocs-section-index
          pip install mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
      - name: Generate sitemap.xml
        run: python scripts/generate_sitemap.py

      - name: Generate scripts/writeups index
        run: python scripts/generate_Grid.py

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
